# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natscope < Formula
  desc "Web UI for browsing NATS JetStream with protobuf decoding"
  homepage "https://github.com/dmit-4884/natscope"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.1/natscope_0.1.1_darwin_amd64.tar.gz"
      sha256 "a2e89f6bf5be589b645ec13c554ae330cfe89c5ad20e8c48951b866fe48a9551"

      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.1/natscope_0.1.1_darwin_arm64.tar.gz"
      sha256 "1ba114d468da2bec6faa90f601a03dd3096d631f5f31dddff7aee8bd10a1231d"

      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.1/natscope_0.1.1_linux_amd64.tar.gz"
      sha256 "908501673dccc30ae62d66a95fd55b01914b050dc09a7c4e9c9bd65fba992155"
      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.1/natscope_0.1.1_linux_arm64.tar.gz"
      sha256 "97f6fdb583864b5c4e6d7357ebeabdbe67f0be21dc86db6582ce18a8fac4c5b7"
      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  test do
    system "#{bin}/natscope", "version"
  end
end
