# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natscope < Formula
  desc "Web UI for browsing NATS JetStream with protobuf decoding"
  homepage "https://github.com/dmit-4884/natscope"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.0/natscope_0.1.0_darwin_amd64.tar.gz"
      sha256 "c350cfec4d51cf7375a5ac94a7f27cae893ed6c194a28d238f2126f047a31c67"

      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.0/natscope_0.1.0_darwin_arm64.tar.gz"
      sha256 "a9cc304db09c45db119ff94deb35ba1c07c613b8f493e802c30396fa4d70a14c"

      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.0/natscope_0.1.0_linux_amd64.tar.gz"
      sha256 "6e1c42b8dd37d6ce24c194842d70450b92958d505102c5383c8c466c53cbe375"
      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.0/natscope_0.1.0_linux_arm64.tar.gz"
      sha256 "ade05826156e8e1653b5267b83ea2e40184ae0dfca867e840c1271b651426239"
      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  test do
    system "#{bin}/natscope", "version"
  end
end
