# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Natscope < Formula
  desc "Web UI for browsing NATS JetStream with protobuf decoding"
  homepage "https://github.com/dmit-4884/natscope"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.2/natscope_0.1.2_darwin_amd64.tar.gz"
      sha256 "48ecc1cc47d4a247cc870235869ad2eab3d6f29d36049b722e1f9cfc92f303b1"

      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.2/natscope_0.1.2_darwin_arm64.tar.gz"
      sha256 "3bc06aaf4b8e8043c0398bffe27d582a349f58e4f45f194c8b218b675c6a1671"

      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.2/natscope_0.1.2_linux_amd64.tar.gz"
      sha256 "460a58884b18aa0d4ea416887376fc8889ebeab69c9b2368f39f616eb4a9d034"
      define_method(:install) do
        bin.install "natscope"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dmit-4884/natscope/releases/download/v0.1.2/natscope_0.1.2_linux_arm64.tar.gz"
      sha256 "4da6310bd9a37ab849d2686159e9e70cb6d9403b378e194efb666b94f52ae011"
      define_method(:install) do
        bin.install "natscope"
      end
    end
  end

  test do
    system "#{bin}/natscope", "version"
  end
end
